#!/bin/bash

set -e # Exit on error

# Ensure $1 is set
if [ -z "$1" ]; then
    echo "Usage: $0 <db_name> <pubkey>"
    exit 1
fi

# Ensure $2 is set to the pubkey
if [ -z "$2" ]; then
    echo "Usage: $0 <db_name> <pubkey>"
    exit 1
fi

DATE=$(date '+%Y%m%d%H%M%S')
FILENAME=$1-${DATE}.iblcli-backup
FILE=/tmp/${FILENAME}

/usr/bin/ibl db new backup ${FILE} --db $1 --pubkey $2 

mkdir -p /silverpelt/backups/pg/$1

cp ${FILE} /silverpelt/backups/pg/$1

ssh autobackup@orchard mkdir -p /wafflepaw/backups/pg/$1

scp ${FILE} autobackup@orchard:/wafflepaw/backups/pg/$1/${FILENAME}